version: "2.3"
services:   
    sender:
        image: sender
        build:
            context: .
            dockerfile: ./Sender/Dockerfile
        networks:
            - new
        depends_on:
            rabbitmq:
                condition: service_healthy
    receiver:
        image: receiver
        build:
            context: .
            dockerfile: ./Receiver/Dockerfile
        networks:
            - new
        depends_on:
            rabbitmq:
                condition: service_healthy
    rabbitmq:
        image: "rabbitmq:3.8-management"
        ports:
            - "15672:15672"
        networks:
            - new
        healthcheck:
            test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
            interval: 10s
            retries: 5
networks:
    new: