name: dev-check
on:
  pull_request:
    branches:
      - dev
  # push:
  #   branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Handle Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

      - name: Node Version
        run: node -v

      - name: NPM Version
        run: npm -v

      - name: Install Angular Cli
        working-directory: ./frontend
        run: npm install -g @angular/cli

      - name: Angular Version
        run: ng --version

      - name: OS Version
        run: uname -a && uname -r

      - name: OS 32/64 bit
        run: uname -m

      - name: FE Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: FE Lint
        working-directory: ./frontend
        run: ng lint
        
      - name: FE Build
        working-directory: ./frontend
        run : |
              ng build --prod --aot
              cd dist
              tar -zcvf ika.tar.gz ika
              ls -a
              sudo sshpass -p ${{ secrets.IKA_PASS }} scp -v -o StrictHostKeyChecking=no -r ika.tar.gz ${{ secrets.IKA_USER }}@${{ secrets.IKA_IP }}:/var/www/html/angular/ika/frontend/dist/

      - name: SER Install dependencies
        working-directory: ./server
        run: npm install
        
      - name: SER Prettier
        working-directory: ./server
        run: npm run prettier-check
        


